### ISSUE TITLE
socket error Error: read ECONNRESET

### ISSUE THREAD

**Issue by simonmorley** [dhbaird/easywsclient#11]
Hi David, was just about the start looking at the SSL stuff but we've run into this problem connecting to the Socket.io server... I'm trying to figure out whether it's the client, Socket.io or NodeJS.

I have raised an issue with Socket.io but I'm still not sure it's their side (see link 1). Struggling to debug it.

The problem only affects some clients, so we're trying to figure that too. It connects to the socket.io server ok, handshake done (I will document for you shortly).

However the first disconnect throws this error:

```
info  - socket error Error: read ECONNRESET
at errnoException (net.js:901:11)
at onread (net.js:556:19)
```

And doesn't clear the session properly (hence I thought it was node or socket.io). When you reconnect the client and disconnect again, you get this:

```
at Readable.on (_stream_readable.js:679:33)
at Transport.setHandlers (node_modules/socket.io/lib/transport.js:115:15)
at Transport.handleRequest (node_modules/socket.io/lib/transport.js:70:10)
at Transport (node_modules/socket.io/lib/transport.js:31:8)
at new WebSocket (node_modules/socket.io/lib/transports/websocket/hybi-16.js:59:13)
at new WebSocket (node_modules/socket.io/lib/transports/websocket.js:31:17)
at Manager.handleClient (node_modules/socket.io/lib/manager.js:662:19)
at Manager.handleUpgrade (node_modules/socket.io/lib/manager.js:618:8)
```

NodeJS needs to be restarted to accept a connection again.

Because we have most clients (Linux and Mac) working, I genuinely don't think it's client side. However, you're clearly a socket genius and was hoping you might have some thoughts?

-- EDIT -- 

We're actually getting this on some Ubuntu builds too.. Still trying to narrow it down..
1. https://github.com/LearnBoost/socket.io/issues/1281

**Comment by EvanCarroll** [comment]
Blast from the past, but I'm still getting this on node v11.6

**Comment by EvanCarroll** [comment]
Here is how this problem is generated. It's generated when the client itself closes the connection with 

    ws = new WebSocket(`${baseURL}`);

And then

    ws.close();


And then the server calls 

    wsServer.close();

Before it knows the connection is closed. In the case of a test-teardown that's common. What you should do is provide the callback to `wsServer.close()`

    wsServer.close( ws => ws.close() )
