### ISSUE TITLE
wait/poll function?

### ISSUE THREAD

**Issue by donpillou** [dhbaird/easywsclient#23]
Hello and thank you for sharing easywsclient,

right now easywsclient does not allow us to wait for arriving data via a nonblocking recv or select/poll. I guess some projects might be ok with that, but actually this is kinda illogical. The point of Websockets is to avoid active polling and hence, it would be nice if easywsclient provides a mechanism (e.g. a blocking function) to wait for data.

Best regards, 
Donald Pillou

**Comment by oboolean** [comment]
@donpillou 
I just realized that if someone is sending data, the call to select will return immediately and hence there is no delay.
how to do that
