### ISSUE TITLE
receiving binary data

### ISSUE THREAD

**Issue by krapskill** [dhbaird/easywsclient#38]
Hi dhbaird,

It seems we cannot receive binary data with your library...
Is it me who didn't manage to work with correctly or it is true ?

(i sent you an email about that btw)

"ERROR: Got unexpected WebSocket message." when trying to receive binary data
from line 315 of easywsclient.cpp

Do you think you can help me  in any way ?

thx

**Comment by vinodkumar4a5** [comment]
Hi dhbaird,
                I am trying to implement SSL(wss) connection on top of your library. But i am not getting any idea regarding that. Can you please guide me how to that.

Thanks

**Comment by dhbaird** [comment]
@vinodkumar4a5, kindly go to issue #39 which documents SSL. Thank you.
