### ISSUE TITLE
no timeout and faster socket error detection

### ISSUE THREAD

**Issue by fourtytoo** [dhbaird/easywsclient#41]
I needed these features: an infinite timeout and a faster socket death detection.
If you are interested, here are the patches:

--- /Users/wpelissero/tmp/easywsclient/easywsclient.cpp	2015-08-20 12:49:06.000000000 +0200
+++ easywsclient.cpp	2015-08-28 17:58:17.000000000 +0200
@@ -188,15 +188,25 @@
             }
             return;
         }
-        if (timeout > 0) {
+        if (timeout != 0) {
             fd_set rfds;
             fd_set wfds;
+            fd_set efds;
             timeval tv = { timeout/1000, (timeout%1000) * 1000 };
             FD_ZERO(&rfds);
             FD_ZERO(&wfds);
+            FD_ZERO(&efds);
             FD_SET(sockfd, &rfds);
             if (txbuf.size()) { FD_SET(sockfd, &wfds); }
-            select(sockfd + 1, &rfds, &wfds, NULL, &tv);
+            FD_SET(sockfd, &efds);
+            select(sockfd + 1, &rfds, &wfds, &efds, timeout > 0 ? &tv : 0);
+            if (FD_ISSET(sockfd, &efds))
+            {
+                closesocket(sockfd);
+                readyState = CLOSED;
+                fputs("Connection error!\n", stderr);
+                return;
+            }
         }
         while (true) {
             // FD_ISSET(0, &rfds) will be true

**Comment by dhbaird** [comment]
Hi @fourtytoo. I just noticed your message. Thanks for taking the time to post this. Could possibly reformat this into a pull request? This is for two reasons: (1) you get credit if the patch is merged, and (2) the formatting is a little bit better than it is here. Thanks.

**Comment by fourtytoo** [comment]
Just did.
Cheers

**Comment by dhbaird** [comment]
#43 closes this ticket.
