### ISSUE TITLE
close method doesn't work

### ISSUE THREAD

**Issue by chrisfw** [dhbaird/easywsclient#44]
Hi,

I was exercising easywsclient using the test code and one of my use cases requires a short-lived websocket where the client will issue a close.  When I tested it, I noticed that my server never received the close message prior to the client exiting.  In looking at the source, it appears that the buffer with the close message is constructed but never sent.  I am not a C++ dev, but it looked to me like I needed to add the send, etc. (int ret = ::send(sockfd, (char*)&txbuf[0], txbuf.size(), 0);)  I did so in my test program and it worked - the server now sees the close message come through.  Could you please incorporate this/a fix in for this issue when you have a chance as I am not sure that my fix implementation is complete?

Regards,

Chris Whelan

 void close() {
        if(readyState == CLOSING || readyState == CLOSED) { return; }
        readyState = CLOSING;
        uint8_t closeFrame[6] = {0x88, 0x80, 0x00, 0x00, 0x00, 0x00}; // last 4 bytes are a masking key
        std::vector<uint8_t> header(closeFrame, closeFrame+6);
        txbuf.insert(txbuf.end(), header.begin(), header.end());
        int ret = ::send(sockfd, (char*)&txbuf[0], txbuf.size(), 0);
        if (ret <= 0) {
          closesocket(sockfd);
          readyState = CLOSED;
          fputs(ret < 0 ? "Connection error!\n" : "Connection closed!\n", stderr);
        }

    }

**Comment by chrisfw** [comment]
This appears to have been a problem with a sleep call in my test program.  My updated code works fine on both AIX on Linux

**Comment by dhbaird** [comment]
Hi Chris, thank you for taking the time for this issue (and also to diagnose/close). If you notice anything else, you are very invited to make a report again. Thanks!

**Comment by chrisfw** [comment]
No problem David!  Will do.

Regards,

Chris
