### ISSUE TITLE
Receive Messages

### ISSUE THREAD

**Issue by thirdlastletter** [dhbaird/easywsclient#50]
Hi!
awesome Client! I was able to implement it.

Does anyone have an example how to receive messages? I am having trouble using the dispatch().

Thanks!

**Comment by dhbaird** [comment]
Hi @thirdlastletter, what did you try so far? The example-client.cpp file shows how to use dispatch().

**Comment by thirdlastletter** [comment]
Hi,
I implemented the example-client.cpp, sending seems to be working, but it isn't showing any received messages.

**Comment by dhbaird** [comment]
I would recommend using Wireshark to look at the network packets.

**Comment by rudakovdg** [comment]
Hi, i have the same problem, after a connection and sending first message to Bitfinex I recieve only one message {"event":"info","version":1.1} (means that connection established), and none of any other messages from server (there should be feed of JSON messages). I checked network with Wireshark - all is ok, and the same code on python recieves all messages. What might be the problem?
