### ISSUE TITLE
vector iterator not dereferencable

### ISSUE THREAD

**Issue by RobsonMi** [dhbaird/easywsclient#57]
When trying to send this string:

`{"action":"update_state","payload":"AAAAAMzMzMxNGmLY1H8+QP5ii+m4oFXASc3y6bEFaEAaCsUgRmrCv2vYrK5+3Xq/AN/IeeM0Mj8AQNtpk4OgvgCAUXNX3Vc/n5bAlyZReD+wcAa4kTIWP8G7Y97RYFlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8///UWd5eD+a168NGC5XvgAAACCVQmw/AAAAAMzMzMw=","type":"sim_packet"}`

I get error `Expression: vector iterator not dereferencable`. I happens in easywsclient.cpp in sendData function at line 413:
`if (useMask) {
            for (size_t i = 0; i != message_size; ++i) { *(txbuf.end() - message_size + i) ^= masking_key[i&0x3]; }
        }`
Then call stack points to vector operator*().

Any ideas why this happens? Other messages are sent without issues.

**Comment by dhbaird** [comment]
Thanks for reporting this. I'm not yet sure what the root cause is, but can you try this branch (issue/57-vector-iterator-not-dereferencable) and see if it helps?

https://github.com/dhbaird/easywsclient/tree/issue/57-vector-iterator-not-dereferencable

**Comment by Good4m** [comment]
This worked for me thanks

**Comment by dhbaird** [comment]
@RobsonMi, if you still observe this issue, please reopen ticket. Thanks.
