### ISSUE TITLE
Having more callbacks for error handling / change of state (disconnect -> connected)

### ISSUE THREAD

**Issue by bsergean** [dhbaird/easywsclient#58]
Hi there,

I've started using this code and it's pretty awesome how easy it was to integrate in our current C++ project. There is one that is missing though is that I would like to have callbacks being executed when some operation happens; here are 2 examples:

* The socket got connected
* We got disconnected.

This would help us propagate that info upstream to other piece of the code, for example so that we can display a dialog such as "reconnecting", or "disconnected" when we are ... disconnected.

This can probably be implemented without breaking backward compatibility, by registering additional callbacks, or maybe only one that will work with enums or such.

Also the errors that are printed on the terminal through *fprintf* cannot be used by other code. I wonder if there should be some kind of callback there. Some function could return error messages as std::string by reference too, which is a pattern I've often used to propagate errors. Although this doesn't work very well when the error is too "far" from the call site.

I might try to prototype something and send a Pull request, but I wanted to get the maintainer opinion first before I go in a wrong direction, because I would love this work to be merged in if it is generic enough.

Thanks !

**Comment by bsergean** [comment]
Here's the web browser api:

![ws-1024x369](https://user-images.githubusercontent.com/11857745/28882576-7dc5291e-7760-11e7-9b7d-bc7093d7fac1.png)

I don't think that we need the onmessage callback, but maybe we could use the other 3 ones, onerror, onclose, and onerror. There's another C++ library that has similar callbacks, actually a lot more. Maybe we don't need that many but those 3 I'm describing sounds like a good start -> https://github.com/zaphoyd/websocketpp/blob/master/websocketpp/connection.hpp

**Comment by bsergean** [comment]
Read the web document a little further, and onclose is actually the only event that will carry a description of the "error". The other events do not carry any extra information.

**Comment by oboolean** [comment]
@bsergean  good idea
 do you implement those callback  onopen onerror onclose onmessage ...

**Comment by bsergean** [comment]
Yeah I implemented those callbacks in my now heavily modified version of this (great) library. I should find a way to contribute it to this project or make a sister standalone project.

I also have SSL support on iOS and Android, macOS and Linux (didn't do anything on Windows though). What I did is make an abstraction for the socket transport. I reused a lot of SSL code from the satori C sdk, which is a C library that builds on top of web socket to give a pubsub with advanced features (such as SQL like queries) -> https://github.com/satori-com/satori-rtm-sdk-c/tree/master/core/src

**Comment by dhbaird** [comment]
Hi! I do support sending a pull request, with the following properties:

- Doesn't break backwards compatibility.
- Follows the style of the current code.
- Includes some integration tests in the `test/` folder.

Making an abstraction for the socket transport sounds like the right way to go for SSL. I could look at the code, if you have a link handy, and give pre-pull-request feedback if you'd like.

Thanks for looking into this issue.

**Comment by bsergean** [comment]
Great, I'll see what I can do ... I hope I'll have time to take the time to do it ... :)

BTW thanks so much for writing this library in the first place, it has helped us tremendously.

**Comment by bsergean** [comment]
We finally open-sourced our library, here it is:

https://github.com/machinezone/IXWebSocket

**Comment by bsergean** [comment]
Hey I won't need this that much now that we have our hacked-up version of easywsclient (btw I just added Windows support for it by again looking at easywsclient).

Closing to have less noise on the bug tracker.
