### ISSUE TITLE
add onreceivedmessage function

### ISSUE THREAD

**Issue by developernew123** [dhbaird/easywsclient#68]
add onreceivedmessage function to be a handler for messages so that I don't use poll() and dispatch() very many times

**Comment by dhbaird** [comment]
An onreceivedmessage handler isn't straightforward, and I do agree it would be nice though, but do you think you could do this instead?
- Run poll() / dispatch() in a separate thread, so that it doesn't block your main thread. This would get you pretty close to "onreceivedmessage."

**Comment by developernew123** [comment]
yes it would but wouldn't this make anything to the send() ?

**Comment by developernew123** [comment]
when I use it as a thread it doesn't send

**Comment by developernew123** [comment]
It worked well I was using the thread after the return of the function which made it fail
